version: "3"
services:
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    command:
    - --transaction-isolation=READ-COMMITTED
    - --binlog-format=ROW
    - --log-bin=mysqld-bin
    volumes:
    - ./data/mysql:/var/lib/mysql
    environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
  nextcloud:
    image: nextcloud:${NEXTCLOUD_VERSION}
    volumes:
    - ./data/nextcloud:/var/www/html
    environment:
    - MYSQL_HOST=mariadb:3306
    - MYSQL_DATABASE=nextcloud
    - MYSQL_USER=nextcloud
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - NEXTCLOUD_ADMIN_USER=admin
    - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
    - NEXTCLOUD_TRUSTED_DOMAINS=localhost nextcloud ${DOMAIN} ${IP_ADDRESS}
  traefik:
    image: traefik:v${TRAEFIK_VERSION}-alpine
    ports:
    - 80:80
    - 443:443
    - 8083:8083
    volumes:
    - ./secret:/secret
    - ./traefik.toml:/traefik.toml
    command:
    - -c
    - /traefik.toml
  collabora:
    # TODO: Expose this through the Traefik reverse proxy
    image: collabora/code:${COLLABORA_VERSION}
    ports:
    - 9980:9980
    environment:
    - domain=${REGEXP_DOMAIN}
    - dictionaries=en
    cap_add:
    - MKNOD
    tty: true
