checkNewVersion = false
defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    compress = true
    [entryPoints.https.tls]
      minVersion = "VersionTLS12"
      [[entryPoints.https.tls.certificates]]
        certFile = "/secret/nextcloud.crt"
        keyFile = "/secret/nextcloud.key"

  [entryPoints.api]
    address = ":8083"

[api]
entryPoint = "api"

[file]
# Backends
[backends]
  [backends.nextcloud]
  [backends.nextcloud.servers]
  [backends.nextcloud.servers.server0]
    url = "http://nextcloud"

[frontends]
  [frontends.nextcloud]
    entryPoints = ["http", "https"]
    backend = "nextcloud"
    passHostHeader = true
    [frontends.nextcloud.headers.customresponseheaders]
    Strict-Transport-Security = "15552000"
    [frontends.nextcloud.whiteList]
      useXForwardedFor = true

# Metrics definition
[metrics]
  # To enable Traefik to export internal metrics to Prometheus
  [metrics.prometheus]
  entryPoint = "api"
